initial research
ZPP-MURMURAS/ZPP_Murmuras pull request #12
Opened 2024-11-06 09:33 UTC by SzymonKozl

Results not promising at this moment

2024-11-14 19:13 UTC, SzymonKozl commented
closing this for now as the results seems to be useless

2024-11-14 19:13 UTC, SzymonKozl commented
closing this as results seems useless

2024-11-28 19:48 UTC, GustawB commented
@SzymonKozl weren't we supposed to merge this at some point?

2024-12-19 20:28 UTC, GustawB requested changes

2024-12-19 20:28 UTC, GustawB commented on research/preprocessing_szymon/data/18789327023.csv
Please remove this file.

2024-12-19 20:28 UTC, GustawB commented on research/preprocessing_szymon/grouping.ipynb
> +    "##### The purpouse of this notebook was to test different approach to grouping labels\n",
```suggestion
    "##### The purpose of this notebook was to test different approaches to the labels grouping problem\n",
```

2024-12-19 20:28 UTC, GustawB commented on research/preprocessing_szymon/grouping.ipynb
> +    "##### Algorithm hyperparameters"
```suggestion
    "##### Algorithm's hyperparameters"
```

2024-12-19 20:28 UTC, GustawB commented on research/preprocessing_szymon/grouping.ipynb
> +    "The hyperparameters above were choosen as result of empirical experiments. The results show that this method currently cannot provide robust label grouping in case of sparse data. Research on la
I know that I wasn't supposed to be requesting everything, BUT for the sake of completeness I would elaborate why those results are bad.  At least at first glance, these results doesn't look that bad (at least in the context of out recent results on PoC).

2024-12-26 16:09 UTC, GustawB requested changes

2024-12-26 16:09 UTC, GustawB commented on research/preprocessing_szymon/grouping.ipynb
> +    "Firtly we compute distances between neighbour labels. Then we aggregate them and count duplicated vectors. To handle vector storing and querying I used vectorDB. Finally, I created groups by con
```suggestion
    "Firstly we compute distances between neighbour labels. Then we aggregate them and count duplicated vectors. To handle vector storing and querying I used vectorDB. Finally, I created groups by connecting labels if distance between them is common."
```

2024-12-27 09:19 UTC, GustawB approved these changes
LGTM

2024-12-27 09:19 UTC, merged