23 research onnx deployment on mobile
ZPP-MURMURAS/ZPP_Murmuras pull request #34
Opened 2024-11-22 12:24 UTC by nawiju

deployed onnx model on mobile

2024-11-28 19:34 UTC, GustawB requested changes
Ok so first of all, a very trivial thing, but I would change the name of the subdirectory of this research to something that indicates that this is related to ONNX (e.g. ONNXDeployment).

Now, at least for me right now this app doesn't work. I cloned the mobile bert repo, I ran the script, but the code you provided doesn't recognize names "mobilebert" and "bert_model_quantized". I attach screenshots of errors and my project layout. Is there something I'm missing? 

![image](https://github.com/user-attachments/assets/ac850926-59e6-4265-b42b-217627116b69)

![image](https://github.com/user-attachments/assets/56d3432b-c027-448d-bed5-36fb099960be)

2024-11-28 19:34 UTC, GustawB commented on research/BertDemoApp/README.md
> +git clone https://huggingface.co/google/mobilebert-uncased
Does it matter where we clone it? Please elaborate on that

2024-11-28 19:34 UTC, GustawB commented on research/BertDemoApp/README.md
> +git lfs install  # Install Git Large File Storage if you haven't already.
It's not that trivial. I suggest that you include a link to the tutorial: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#about-commit-email-addresses

2024-11-28 19:34 UTC, GustawB commented on research/BertDemoApp/README.md
> +Then run this script.
Please add this and the script above to the .py file. While running two-three lines of code from the terminal is not a problem, running a whole script is annoying.

2024-11-28 19:34 UTC, GustawB commented on research/BertDemoApp/README.md
> +Download any missing libraries etc.
Please add requirements.txt

2024-11-28 19:34 UTC, GustawB commented on research/BertDemoApp/screenshot1.jpg
I would rename it to something meaningful and move it to a dedicated subdirectory (I understand it's just one file, but then you add something else, then again you add something, and suddenly you have multiple different files in one dir.)

2024-11-28 19:34 UTC, GustawB commented on research/BertDemoApp/android/README.md
Ig this file is not needed (doesn't describe our app). Also, if you used a ready template from a tutorial and built on top of it, just in case I would check what kind of licencing it has.

2024-11-28 19:34 UTC, GustawB commented on research/BertDemoApp/android/images/screenshot_2.jpg
Do we need this whole subdirectory?

2024-11-28 19:34 UTC, GustawB commented on research/BertDemoApp/android/settings.gradle
> +rootProject.name = "ort_image_classifier"
I think this should be changed

2024-12-02 23:46 UTC, nawiju commented
> Ok so first of all, a very trivial thing, but I would change the name of the subdirectory of this research to something that indicates that this is related to ONNX (e.g. ONNXDeployment).
> 
> Now, at least for me right now this app doesn't work. I cloned the mobile bert repo, I ran the script, but the code you provided doesn't recognize names "mobilebert" and "bert_model_quantized". I attach screenshots of errors and my project layout. Is there something I'm missing?
> 
> ![image](https://private-user-images.githubusercontent.com/93836926/390892415-ac850926-59e6-4265-b42b-217627116b69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODMyNzksIm5iZiI6MTczMzE4Mjk3OSwicGF0aCI6Ii85MzgzNjkyNi8zOTA4OTI0MTUtYWM4NTA5MjYtNTllNi00MjY1LWI0MmItMjE3NjI3MTE2YjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDIzNDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYzhjODAzYmU4YzJiYjAwNDQ5YmNjOGQxOTA5YWE1MzQzNzMzNDhkNjQ2Y2I2YjgxYTFjZmVlNGNlNjJhMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dtCtei9D5mmuwjM3HzoMal8_KfNEBvXCflaq820EMN8)
> 
> ![image](https://private-user-images.githubusercontent.com/93836926/390892447-56d3432b-c027-448d-bed5-36fb099960be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODMyNzksIm5iZiI6MTczMzE4Mjk3OSwicGF0aCI6Ii85MzgzNjkyNi8zOTA4OTI0NDctNTZkMzQzMmItYzAyNy00NDhkLWJlZDUtMzZmYjA5OTk2MGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDIzNDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiOGUzNTk2NzM4N2IxMTczNzkwNmU1NzRhNjZmNTA0YTdlNDIyMTBkODdlYzY2MzJjMDg0MWZkOThiMjhhZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4rlZLw2RHKtF23udN1y7pNPAaeWTuQ2RWxjA5TYW5R4)

Did you put the mobilebert in the app/src/main/res/raw directory?

2024-12-03 12:29 UTC, GustawB requested changes
1. BertDemoApp: this is example of ONNX, not bert, change naming
2. What is bert_base_uncased? 
![image](https://github.com/user-attachments/assets/2a21c8f8-6f72-4af6-9eaf-cd667fdaf095)
3. Do we even use the repo we clone for bert?
4.  If you added script file and requirements, pip install part and script can be removed from the README
5. This is on me, I provided you with the wrong link for the git lfs so its nice that you found it, BUT, if you see that I send something stupid, you can reply to my comment instead of just blindly following my every order.
6. I moced the mobilebert.onnx to th elocation you specified and everything started working. But it would be nice if this was described in the README.
7. App is running but not necessary working (though I removed the bert_base_uncased so yambe that's why)
![image](https://github.com/user-attachments/assets/7cb4a21e-aa2a-4960-9bef-87f346707de4)
8. Is it possible to analyze text, and then analyze another? It doesn't seem to work more than once, but maybe it's because I'm getting the same output for every query

2024-12-05 15:10 UTC, GustawB approved these changes

2024-12-05 17:21 UTC, merged