dirty version of fine-tuning on our 'dataset', not tested yet
ZPP-MURMURAS/ZPP_Murmuras pull request #36
Opened 2024-11-26 12:35 UTC by SzymonKozl

2024-11-26 12:38 UTC, SzymonKozl commented
At this moment this code is WIP

2024-11-28 19:47 UTC, GustawB requested changes
Looks alright, but I think it would be nice if you:
1. Added a short intro describing why are you researching this approach
2. There isn't much description of what's going on throught the file; while in most places it's non-problematic, at some point in notebook you get some kind of result and say that "it's bad". After you explanation on weekly today I know why, but without it, all I see is a low score and some  start and end indexes. I would elaborate on what does this result represent and then why this particular one is bad.

You can also elaborate somewhere (ig at the beginning) what QA does (this connects with describing why you research it, but it's important because it will also make it more clear why e.g. results you obtain are good/bad).

2024-11-28 19:47 UTC, GustawB commented on research/question_answering_approach/ds/18929485529.csv
didn't we discuss with Murmuras at some point that this data should not be shared (this repo is public)?

2024-12-03 20:13 UTC, SzymonKozl commented on research/question_answering_approach/ds/18929485529.csv
removed

2024-12-05 15:17 UTC, GustawB requested changes

2024-12-05 15:17 UTC, GustawB commented on research/question_answering_approach/qa_finetuning.ipynb
> +    "I did not find and fine-tunes of BERT on xml or even html. Although there are llama models finetuned for RAG, task similar to QA working with HTML data (like zstanjj/HTML-Pruner-Llama-1B).\n"
```suggestion
    "I did not find or fine-tuned any BERT model on xml or even html. Although there are llama models finetuned for RAG, task similar to QA working with HTML data (like zstanjj/HTML-Pruner-Llama-1B).\n"
```

2024-12-05 15:17 UTC, GustawB commented on research/question_answering_approach/qa_finetuning.ipynb
> +    "tldr: idk </br>\n",
Hmm, not sure if I understand; can we talk irl about this?

2024-12-06 17:44 UTC, SzymonKozl commented on research/question_answering_approach/qa_finetuning.ipynb
> +    "I did not find and fine-tunes of BERT on xml or even html. Although there are llama models finetuned for RAG, task similar to QA working with HTML data (like zstanjj/HTML-Pruner-Llama-1B).\n"
This correction changes meaning of this sentence. I propose rather:
```suggestion
    "I did not find any fine-tuned versions of BERT on xml or even html. Although there are llama models finetuned for RAG, task similar to QA working with HTML data (like zstanjj/HTML-Pruner-Llama-1B).\n"
```

2024-12-10 18:33 UTC, GustawB approved these changes

2024-12-11 10:11 UTC, merged