15-move-datasets-to-google-drive
ZPP-MURMURAS/ZPP_Murmuras pull request #44
Opened 2024-12-03 20:38 UTC by SzymonKozl

2024-12-09 17:40 UTC, GustawB requested changes
Waiting for credentials to check if it works; but rn LGTM.

2024-12-09 17:40 UTC, GustawB commented on research/preprocessing/clustering/cluster_research.ipynb
> +    "this notebook requires `coupons_0` dataset downloaded and moved to `./data` folder. Please follow dataset download instructions from Way of Work doc."
```suggestion
    "this notebook requires `coupons_0` dataset downloaded and moved to `./data` folder. Please follow dataset download instructions from the README in docs/."
```

2024-12-09 17:40 UTC, GustawB commented on docs/README.md
> +pyhton tools/data_load.py <ds_name>
```suggestion
python tools/data_load.py <ds_name>
```

2024-12-09 21:23 UTC, GustawB requested changes

2024-12-09 21:23 UTC, GustawB commented on tools/data_load.py
> +CREDENTIALS_PATH = 'tools/gdrive_credentials.json'
```suggestion
CREDENTIALS_PATH = 'gdrive_credentials.json'
```

gdrive_credentials will be in the same folder as this script (at least if I understood the README correctly). So, revious version doesn't work.

2024-12-11 10:18 UTC, SzymonKozl commented on tools/data_load.py
> +CREDENTIALS_PATH = 'tools/gdrive_credentials.json'
changed

2024-12-12 13:00 UTC, merged