56 research on text sections classificaton
ZPP-MURMURAS/ZPP_Murmuras pull request #58
Opened 2024-12-17 09:43 UTC by SzymonKozl

WIP

2024-12-26 17:54 UTC, kdybek requested changes
Looks great. Though, why is it a python notebook if there is no python code in it?

2024-12-26 17:54 UTC, kdybek commented on research/second_llm_pass/notes.ipynb
> +    "This solution is conceptually similar to multi-answer QA. For each token we assign a label being `UNKNOWN`, `BEGIN-COUPON`, `MID-COUPON` or `END-COUPON`. This time, however, we will use CNNs. </
Wouldn't UNKNOWN, BEGIN-COUPON and MID-COUPON labels suffice?

2024-12-27 06:59 UTC, SzymonKozl commented on research/second_llm_pass/notes.ipynb
> +    "This solution is conceptually similar to multi-answer QA. For each token we assign a label being `UNKNOWN`, `BEGIN-COUPON`, `MID-COUPON` or `END-COUPON`. This time, however, we will use CNNs. </
You are right, we do not need END-COUPON indeed.

2024-12-27 07:03 UTC, SzymonKozl commented
I have started noting in  .ipynb to leave myself an option to add some code if needed. It turned out to be unnecessary. I will convert this to .md format.

2024-12-30 09:55 UTC, kdybek approved these changes
LGTM

2025-01-02 07:28 UTC, merged