Test and fine-tune different Llama models owith Llama.cpp lib.
ZPP-MURMURAS/ZPP_Murmuras pull request #59
Opened 2024-12-21 14:05 UTC by GustawB

2025-01-03 20:05 UTC, SzymonKozl requested changes
Thanks, great job.
Few small suggestions from me and one question.
I hope that benchmarks results were affected by your phone's problems - 30 tokens/s is probably not enough for our case.

2025-01-03 20:05 UTC, SzymonKozl commented on research/llama_cpp/inference/inference.ipynb
> +    "## 4.1 Laptop performance (16gb ram)\n",
explain please what does "pp512" and "tg128" mean

2025-01-04 08:47 UTC, GustawB commented on research/llama_cpp/inference/inference.ipynb
> +    "And I am happy to announce that I proved my hypothesis. I run both explicitly supported models: [Llama 2-7B](https://huggingface.co/meta-llama/Llama-2-7b-hf) and [Llama 3-8B](https://huggingface
You mean this?
![image](https://github.com/user-attachments/assets/8fb6b64c-0678-4cc1-9503-65d09a86aa60)

2025-01-04 08:49 UTC, GustawB commented on research/llama_cpp/inference/inference.ipynb
> +    "## 4.1 Laptop performance (16gb ram)\n",
Done

2025-01-04 08:55 UTC, SzymonKozl commented on research/llama_cpp/inference/inference.ipynb
> +    "And I am happy to announce that I proved my hypothesis. I run both explicitly supported models: [Llama 2-7B](https://huggingface.co/meta-llama/Llama-2-7b-hf) and [Llama 3-8B](https://huggingface
yes

2025-01-04 09:28 UTC, GustawB commented on research/llama_cpp/inference/inference.ipynb
> +    "And I am happy to announce that I proved my hypothesis. I run both explicitly supported models: [Llama 2-7B](https://huggingface.co/meta-llama/Llama-2-7b-hf) and [Llama 3-8B](https://huggingface
Nvm, I got what you meant. Done.

2025-01-04 09:48 UTC, GustawB commented on research/llama_cpp/inference/inference.ipynb
> +    "As mentioned before, older models and/or models with stronger quantizations may not generate the \"[end of text]\" token and will generate data infinitely/will repeat it a few times before finis
Probabilities per-se, I don't think so; I found two threads on github:
https://github.com/ggerganov/llama.cpp/issues/1784
https://github.com/ggerganov/llama.cpp/issues/6285
that suggest that we would need to modify the logic inside the llama.cpp code if we want to get those probs/logits.

Alternatively, we could play with other options from the llama.cpp: XTC sampling (https://github.com/ggerganov/llama.cpp/issues/6285) which removes most probable tokens, or with Logit Bias (https://github.com/ggerganov/llama.cpp/issues/6285) to boost the probability of the EOS token.

Finally, by accident, I found out about this: https://github.com/abetlen/llama-cpp-python
This lib contains python bindings for llama.cpp so it can be used in python scripts. More research on this would be needed, but this thread: https://stackoverflow.com/questions/78909701/how-to-use-llama-cpp-python-to-output-list-of-candidate-tokens-and-their-proba suggests that we can then easily extract logits.

2025-01-04 10:55 UTC, SzymonKozl commented on research/llama_cpp/inference/inference.ipynb
> +    "As mentioned before, older models and/or models with stronger quantizations may not generate the \"[end of text]\" token and will generate data infinitely/will repeat it a few times before finis
Thanks for those proposals. We probably should explore them more if this still will be problematic after fine-tuning. I also hope that they do not downgrade performance significantly.

2025-01-04 10:55 UTC, SzymonKozl approved these changes

2025-01-04 20:57 UTC, merged