added executorch_llama_report.md
ZPP-MURMURAS/ZPP_Murmuras pull request #60
Opened 2024-12-24 12:38 UTC by kdybek

2024-12-26 08:34 UTC, SzymonKozl requested changes
well done, 2 small questions from me

2024-12-26 12:18 UTC, SzymonKozl requested changes

2024-12-26 12:18 UTC, SzymonKozl commented on research/executorch/executorch_llama_report.md
> +# Benchmarking
Thanks for explanation. Maybe short note that XNNPACK is library that can be built on most of mobile phones would be helpful (I do not find this obvious and It required me few minutes of googling)

2024-12-26 16:03 UTC, GustawB requested changes
Good job. I have two comments, and one more thing: my understanding was that both you and me will fine-tune an example Llama. I guess on one hand it doesn't make sense for both of us to do this, but on the other,  I will be using HuggingFace approach for this, so maybe you'll need a different approach for executorch? So I guess my question here is how do we proceed? @SzymonKozl @nawiju any insight?

2024-12-26 17:15 UTC, kdybek commented on research/executorch/executorch_llama_report.md
> +The repository includes a [benchmarking section](https://github.com/pytorch/executorch/blob/main/examples/models/llama/README.md) where different Llama models are tested on edge devices using the XNN
There is a link to those results.

2024-12-26 17:29 UTC, SzymonKozl approved these changes

2024-12-26 17:49 UTC, SzymonKozl commented on research/executorch/executorch_llama_report.md
> +There is a [demo Llama application](https://github.com/pytorch/executorch/tree/main/examples/demo-apps/android/LlamaDemo) in the repository. Executorch supports various backends for running models, i
1. There is no need to perform full fine-tuning twice - It would be waste of resources. I see that on HF Llama-3.2-1B model has pytorch backend. Can we use weights from model like that to initialize llama-cpp @GustawB? If yes, fine-tuning in standard HF loop is imo the best option as we could deploy resulting model in both ways.
2. We still do not know which option is faster - llamaCpp or executorch. Bechmarks provided suggest latter, but the results were achieved on more powerfull device. I think that we should run them on the same device to have more reliable info.

2024-12-26 18:03 UTC, kdybek commented on research/executorch/executorch_llama_report.md
> +There is a [demo Llama application](https://github.com/pytorch/executorch/tree/main/examples/demo-apps/android/LlamaDemo) in the repository. Executorch supports various backends for running models, i
+1. Fine tuning should be a separate task imho.

2024-12-26 21:34 UTC, GustawB commented on research/executorch/executorch_llama_report.md
> +The repository includes a [benchmarking section](https://github.com/pytorch/executorch/blob/main/examples/models/llama/README.md) where different Llama models are tested on edge devices using the XNN
On a much powerful device

2024-12-26 21:34 UTC, GustawB commented on research/executorch/executorch_llama_report.md
> +The repository includes a [benchmarking section](https://github.com/pytorch/executorch/blob/main/examples/models/llama/README.md) where different Llama models are tested on edge devices using the XNN
@SzymonKozl please don't resolve my comments

2024-12-26 21:47 UTC, GustawB commented on research/executorch/executorch_llama_report.md
> +There is a [demo Llama application](https://github.com/pytorch/executorch/tree/main/examples/demo-apps/android/LlamaDemo) in the repository. Executorch supports various backends for running models, i
lets talk about this tomorrow

2024-12-27 00:58 UTC, kdybek commented on research/executorch/executorch_llama_report.md
> +The repository includes a [benchmarking section](https://github.com/pytorch/executorch/blob/main/examples/models/llama/README.md) where different Llama models are tested on edge devices using the XNN
If we want reliable results, we need to test llama cpp and executorch on one phone.

2024-12-27 14:33 UTC, GustawB approved these changes

2024-12-27 15:12 UTC, merged