55 benchmark for our pipelines
ZPP-MURMURAS/ZPP_Murmuras pull request #65
Opened 2024-12-28 08:22 UTC by nawiju

2025-01-02 11:55 UTC, SzymonKozl requested changes
There no default dataset provided (or instructions how to get it) - that was a part of the task
Besides that, good job, only 2 small requests from me.

2025-01-02 11:55 UTC, SzymonKozl commented on research/pipeline_benchmark/benchmark.py
> +def _compare_prices(generated_prices: list, expected_prices: list) -> float:
At this moment it is not clear if generated_prices and expected_prices have to be 2 element long. There are many possibilities to fix that, ie. custom type with named tuples, old and new price in separate arguments, probably simple note in docstring will be enough.

2025-01-02 11:55 UTC, SzymonKozl commented on research/pipeline_benchmark/benchmark.py
> +class ProtoCoupon:
I think we can rename this class to simply Coupon as the `proto` prefix in PoC code was added to indicate that we are dealing with set of prices and not final coupon form.

2025-01-04 08:42 UTC, GustawB requested changes
Good work. I have some comments regarding warnings I got in pycharm, but nothing too serious I think

2025-01-04 08:42 UTC, GustawB commented on research/pipeline_benchmark/benchmark.py
> +    return max(0, coupon_difference - length_difference * LENGTH_PENALTY)
In pycharm I get warning about type mismatch (int vs float). Can you fix it? It may negatively inpact the accuracy of the benchmark.

2025-01-04 08:42 UTC, GustawB commented on research/pipeline_benchmark/benchmark.py
> +                    reader.fieldnames):
I get "Expected type 'list', got 'Sequence[str] | None' instead" here

2025-01-04 08:42 UTC, GustawB commented on research/pipeline_benchmark/benchmark.py
> +                    reader.fieldnames):
Same here (Expected type 'list', got 'Sequence[str] | None' instead )

2025-01-11 17:04 UTC, SzymonKozl requested changes

2025-01-11 17:04 UTC, SzymonKozl commented on research/pipeline_benchmark/benchmark.py
> +    similarity, lonely_coupons = judge_pipeline(expected_coupons,
I think now that we want to calculate this metric per file/timestamp and take (maybe weighted) average. 

I do not think we should consider a success situation where pipeline detects coupon A in a file that contains coupon B and coupon B in a file that contains coupon A.
Your thoughts on that?

2025-01-11 17:15 UTC, nawiju commented on research/pipeline_benchmark/README.md
> +python3 benchmark.py -p "python3 proto_pipeline.py"
What error do you get?

2025-01-12 08:22 UTC, SzymonKozl commented on research/pipeline_benchmark/README.md
> +python3 benchmark.py -p "python3 proto_pipeline.py"
suprisingly, it is `FileNotFoundError: [Errno 2] No such file or directory: 'expected/'`
command I have invoked: `python3 benchmark.py -e expected/ -i input/ -p "python3 proto_pipeline.py"`

2025-01-12 08:32 UTC, SzymonKozl commented on research/pipeline_benchmark/README.md
> +python3 benchmark.py -p "python3 proto_pipeline.py"
I am sorry, this was my mistate - I have ran the wrong command

2025-01-12 08:34 UTC, SzymonKozl commented on research/pipeline_benchmark/README.md
> +`ideal_data.json` is a file that the user must create to test the benchmarking script using `proto_pipeline.py`. It contains the expected data that the aforementioned script will modify. It must cont
okay I see this was fixed

2025-01-12 08:35 UTC, SzymonKozl commented on research/pipeline_benchmark/benchmark.py
> +    similarity, lonely_coupons = judge_pipeline(expected_coupons,
This was just random thought rather that change request, but I see you implemented this.
I am happy with the outcome.

2025-01-12 08:35 UTC, SzymonKozl approved these changes

2025-01-12 18:51 UTC, GustawB requested changes

2025-01-12 18:51 UTC, GustawB commented on research/pipeline_benchmark/benchmark.py
> +    import data_load
Unused?

2025-01-13 12:30 UTC, GustawB approved these changes

2025-01-13 21:54 UTC, merged