Add changes to HLD after meetings on 24.10 and 29.10
ZPP-MURMURAS/ZPP_Murmuras pull request #7
Opened 2024-10-29 21:52 UTC by GustawB

Add a new version after team consultation.

2024-11-03 11:07 UTC, SzymonKozl commented
are we ready to merge this? Next updates could be in separate PRs @GustawB

2024-11-03 11:40 UTC, GustawB commented
@SzymonKozl We can merge, but first I will have to fix tex compilation (no new content)

2024-11-05 06:59 UTC, SzymonKozl requested changes

2024-11-05 06:59 UTC, SzymonKozl commented on .github/workflows/main.yml
> +          if git diff -s --exit-code docs/HLD.tex; then
Add also check for refs.bib
```suggestion
          if git diff -s --exit-code docs/HLD.tex docs/refs.bib; then
```

2024-11-06 12:54 UTC, GustawB commented on .github/workflows/main.yml
> +          if git diff -s --exit-code docs/HLD.tex; then
@SzymonKozl done

2024-11-06 13:51 UTC, SzymonKozl approved these changes

2024-11-06 15:11 UTC, merged